apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: websites
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`bigbackstore.kouse.xyz`) || Host(`chad.kouse.xyz`) || Host(`lyrics.kouse.xyz`) || (Host(`matrix.kouse.xyz`) && PathPrefix(`/.well-known/matrix`))
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: websites
      namespace: "websites"
      port: websites
  tls:
    certResolver: default
    domains:
      - main: "kouse.xyz"
        sans:
          - "*.kouse.xyz"

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: websites
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`tts2.kouse.xyz`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: chatterbox-sapphire
      namespace: "websites"
      port: chatterbox
  tls:
    certResolver: default
    domains:
      - main: "kouse.xyz"
        sans:
          - "*.kouse.xyz"
