apiVersion: v1
kind: Service
metadata:
  name: websites
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: websites
    name: websites

---

apiVersion: v1
kind: Service
metadata:
  name: chatterbox-sapphire
spec:
  ports:
  - port: 8004
    protocol: TCP
    targetPort: chatterbox
    name: chatterbox
