apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater-controller
  name: argocd-image-updater-config
data:
  interval: 6h
