apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  app: monitoring

resources:
- namespace.yaml
- grafana
- prometheus
- librespeed
- ingress-route.yaml
- imageupdater.yaml

patchesStrategicMerge:
- volumes_patch.yaml
