apiVersion: v1
kind: Service
metadata:
  name: livekit-server
  labels:
    app.kubernetes.io/name: livekit-server
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - name: rtc-tcp
      port: 7881
      protocol: TCP
      targetPort: rtc-tcp
    - name: turn-tls
      port: 5349
      protocol: TCP
      targetPort: turn-tls
    - name: turn-udp
      port: 3478
      protocol: UDP
      targetPort: turn-udp
  selector:
    app.kubernetes.io/name: livekit-server
