apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/htp
images:
- name: linuxserver/sonarr
  digest: sha256:02b4d538d351d6e35882a021c08e8600fe95d28860fb1dd724b597166e7221ca
- name: linuxserver/radarr
  digest: sha256:270f25698624b57b86ca119cc95399d7ff15be8297095b4e1223fd5b549b732c
- name: linuxserver/bazarr
  digest: sha256:7d0a091a63889ce1e4ac4c90595ebd2c50ba5a5df7039a4f4d2be6c2aed6d4ae
- name: linuxserver/transmission
  digest: sha256:e220cc5f4d10f4d46057cd10136771c48e9d41361627d566805be1ea9c9a29ae
- name: linuxserver/prowlarr
  digest: sha256:d3e9307b320b6772749a2cf8fc2712e9e824c4930b034680ad4d08a9e2f25884
- name: lscr.io/linuxserver/jellyfin
  digest: sha256:df1ccfdd214c39c9ae0595b5800591b52a6f87bbbab1bd4a53dc7be6852cf6b1
- name: linuxserver/nzbget
  digest: sha256:386a143ba9a2307e9163e6c2eed0752258dea7227027f95a626cdc5569816be0
- name: fallenbagel/jellyseerr
  digest: sha256:499fbe958fa4a0c93172a231c14898986556bb28bd5cd569a0f41dbf887b04d7
- name: lscr.io/linuxserver/qbittorrent
  digest: sha256:f430d70c70d1547fded30fbc3181c4750cef354212a5138ab754eba9ba8bd9e1
- name: linuxserver/plex
  digest: sha256:9794cedd30ad205d13efdb5ec8eb7564c9225dd18a1fa9ea99e94d97b8d6c077
- name: linuxserver/lidarr
  digest: sha256:5f58fcb45a15cb33ef153f74b14c724ba073553afdc9b078e7701f15b7ce1433
- name: slskd/slskd
  digest: sha256:5b29d5d04276fe64004f446b97186451b009f778ea6271754739cf0e97889c37
- name: mrusse08/soularr
  digest: sha256:6e7d72e8d734dd620adc4e1c268d0b67df7e0f8956ceaf3ed59411c3c2870ff2
- name: fredrikburmester/streamystats-v2-nextjs
  digest: sha256:da03c501677ca3d6154b5a360f04f8894f7c5fb93c49a0ddc93414ba615a6a65
- name: fredrikburmester/streamystats-v2-job-server
  digest: sha256:5a907259d5309f7b27a9796a4425cf63f066759f79d55f34b6dbd6f997fca6dc
- name: fredrikburmester/streamystats-v2-migrate
  digest: sha256:48b10b1c6a952bf505709415363e3b2ce9fb307efed99b84058fb7fd34df4f4e
- name: ghcr.io/schaka/janitorr
  digest: sha256:9420be46a80eb961ad87af858e4247c49fdfec457e087dfbb65058b21bd6367f
- name: revenz/fileflows
  digest: sha256:6c364d1b408682a2675accf4e354e77aa0f066bac1f15277c06dc33ffeae55b4
