apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/monitoring
images:
- name: grafana/grafana
  digest: sha256:70d9599b186ce287be0d2c5ba9a78acb2e86c1a68c9c41449454d0fc3eeb84e8
- name: prom/prometheus
  digest: sha256:d936808bdea528155c0154a922cd42fd75716b8bb7ba302641350f9f3eaeba09
- name: ghcr.io/librespeed/speedtest
  digest: sha256:fc2e715615705a0c22c2b9c61b6dbc78fb3d83edc11e6a34a8a3bce43f1f1611
