apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/monitoring
images:
- name: grafana/grafana
  digest: sha256:2175aaa91c96733d86d31cf270d5310b278654b03f5718c59de12a865380a31f
- name: prom/prometheus
  digest: sha256:1f0f50f06acaceb0f5670d2c8a658a599affe7b0d8e78b898c1035653849a702
- name: ghcr.io/librespeed/speedtest
  digest: sha256:f7ff9415e51055349d011efe518cfe4f5bb86e9134031c3eb3f69b9950da2040
