apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/monitoring
images:
- name: grafana/grafana
  digest: sha256:2175aaa91c96733d86d31cf270d5310b278654b03f5718c59de12a865380a31f
- name: prom/prometheus
  digest: sha256:3ea2ed3b8cdfe3ff78aa05473a7ad36b916bdf2464c83b06bcd37c1a67620233
- name: ghcr.io/librespeed/speedtest
  digest: sha256:db39e089d5d18ff962c2fcf2d99362bfb936aec22983b46a004e53d2b3b8042b
