apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/monitoring
images:
- name: grafana/grafana
  digest: sha256:2175aaa91c96733d86d31cf270d5310b278654b03f5718c59de12a865380a31f
- name: prom/prometheus
  digest: sha256:2b6f734e372c1b4717008f7d0a0152316aedd4d13ae17ef1e3268dbfaf68041b
- name: ghcr.io/librespeed/speedtest
  digest: sha256:0cbf2f27fe0f2cab5000a15a94d987b07b6e502c715d559cb57de262774fe4c9
