apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/monitoring
images:
- name: grafana/grafana
  digest: sha256:9e1e77ade304069aee3196e9a4f210830e96e80ce9a2640891eccc324b152faf
- name: prom/prometheus
  digest: sha256:1f0f50f06acaceb0f5670d2c8a658a599affe7b0d8e78b898c1035653849a702
- name: ghcr.io/librespeed/speedtest
  digest: sha256:e86212417fa624182d0f41ea8936bf5f778bb51c6d12f6ab45506f03b418461c
