apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/postgresql

images:
  - name: tensorchord/vchord-postgres
    digest: sha256:e1148232e5d97edaf8d8c76e6c7f73dc08371aa05587df293312f749afb7eb38
