apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sillytavern
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`st.kouse.xyz`)
    priority: 0
    services:
    - kind: Service
      name: sillytavern
      namespace: ai
      port: web
  tls:
    certResolver: default
    domains:
      - main: "kouse.xyz"
        sans:
          - "*.kouse.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chatterbox-tts-server
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`tts.kouse.xyz`)
    priority: 0
    services:
    - kind: Service
      name: chatterbox-tts-server
      namespace: ai
      port: web
  tls:
    certResolver: default
    domains:
      - main: "kouse.xyz"
        sans:
          - "*.kouse.xyz"
