apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

commonLabels:
  app: ai

resources:
- namespace.yaml
- sillytavern
- koboldcpp
- ingress-route.yaml

patchesStrategicMerge:
- volumes_patch.yaml
