apiVersion: v1
kind: Service
metadata:
  name: rustdesk-server
spec:
  ports:
  - port: 21115
    protocol: TCP
    targetPort: nat
    name: nat
  - port: 21116
    protocol: TCP
    targetPort: registry
    name: registry
  - port: 21116
    protocol: UDP
    targetPort: connection
    name: connection
  - port: 21117
    protocol: TCP
    targetPort: relay
    name: relay
  - port: 21118
    protocol: TCP
    targetPort: webclient-hbbs
    name: webclient-hbbs
  - port: 21119
    protocol: TCP
    targetPort: webclient-hbbr
    name: webclient-hbbr
  selector:
    run: rustdesk-server
