apiVersion: v1
kind: Service
metadata:
  name: streamystats-v2
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: webui
  selector:
    run: streamystats-v2-nextjs
---
apiVersion: v1
kind: Service
metadata:
  name: streamystats-v2-job-server
spec:
  ports:
  - port: 3005
    protocol: TCP
    targetPort: 3005
    name: api
  selector:
    run: streamystats-v2-job-server
