apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/ai

images:
  - name: ghcr.io/sillytavern/sillytavern
    digest: sha256:8dc43050b9e0036e0eb106a0c0f943763ef4c071139613c49c3237599d8c4f7d
